server:
  port: 11000


mybatis‑plus:
  mapper‑locations: classpath*:mapper/**/*.xml
  type‑aliases‑package: com.zz.*.entity
  configuration:
    map‑underscore‑to‑camel‑case: true
    log‑impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id  # 全局配置主键策略为雪花算法