server:
  port: 11000


mybatis‑plus:
  mapper‑locations: classpath*:mapper/**/*.xml
  type‑aliases‑package: com.zz.*.entity
  configuration:
    map‑underscore‑to‑camel‑case: true
    log‑impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id  # 全局配置主键策略为雪花算法

spring:
  data:
    redis:
      host: 127.0.0.1
      password: 666666
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0